---
title: "Does FED Communication cause immediate and abnormal returns stock market?"
subtitle: "A sentiment analysis on the S&P 500 Stock Market Index"
author:
  - Matthias Farngruber
  - Matriculation Number 1
  - Filip Lukijanovic
  - 11776896
  - Peter Prlleshi
  - Matriculation Number 3
output:
  html_document: default
  pdf_document: default
---

## Abstract {#sec-abstract}

## Literature Review {#sec-literature-review}

The following research project is mostly based on the work done by

## Data {#sec-data}

XYZ

```{r setup, include=FALSE}
library(readxl)
library(tidyr)
library(zoo)
library(dplyr)
library(stargazer)
library(lmtest)
```

```{r Definition of Data, include=FALSE}

setwd(dirname(rstudioapi::getSourceEditorContext()$path))
path<-dirname(rstudioapi::getSourceEditorContext()$path)

Core <- read_excel("./SENTIMENTS_FOMC_FINAL_with_BERT.xlsx")
Core$Date <- as.Date(Core$Date, format = "%d/%m/%Y") # converting the date column
FilterDates<-c(Core$Date)
Core <- Core[, -2]

#################################################################################
Fed_Futures <- read_excel("./FED_FORWARDS.xlsx")
Fed_Futures$Date <- as.Date(Fed_Futures$Date, format="%Y-%m-%d %H:%M:%S")

Fed_Futures<- Fed_Futures %>% 
  mutate(Date = as.Date(Date)) %>%  
  complete(Date = seq.Date(min(Date), max(Date), by="day"))
      
Fed_Futures<-na.locf(Fed_Futures, fromLast = FALSE)
Fed_Futures<- Fed_Futures[Fed_Futures$Date %in% FilterDates,]

#####################################################################################

IR <- read.csv("./DFF.csv")
IR$Date <- as.Date(IR$DATE, format = "%Y-%m-%d") # converting the date column

IR<- IR %>% 
  mutate(Date = as.Date(Date)) %>%  
  complete(Date = seq.Date(min(Date), max(Date), by="day"))

IR <-na.locf(IR, fromLast = FALSE)
IR <- IR[IR$Date %in% FilterDates,][,-1]

#########################################################################

SPX_DE <- read_excel("./SPX_DE.xlsx")

SPX_DE$Date <- as.Date(SPX_DE$Date, format="%Y-%m-%d %H:%M:%S")

SPX_DE<- SPX_DE %>% 
  mutate(Date = as.Date(Date)) %>%  
  complete(Date = seq.Date(min(Date), max(Date), by="day"))

SPX_DE<-na.locf(SPX_DE, fromLast = FALSE)
SPX_DE<- SPX_DE[SPX_DE$Date %in% FilterDates,]

##################################################################################
SPX_price <- read.csv("./HistoricalPrices.csv", header = TRUE)
SPX_price <- SPX_price[,c(1,5)]# choosing only the closing price each day

SPX_price$Date<-as.Date(SPX_price$Date, format = "%m/%d/%y")# converting the date column

SPX_price<-na.locf(SPX_price, fromLast = FALSE)

SPX_return <- SPX_price %>%
  arrange(Date) %>% # Make sure the data is sorted by date in ascending order
  mutate(Daily_Return = log(Close) - log(lag(Close))) 

days_in_year <- 252
# Calculate rolling 3-year average return
SPX_return$Rolling_3Y_Avg_Return <- rollapply(SPX_return$Daily_Return, 
                                             width = 3 * days_in_year, 
                                             FUN = mean, 
                                             by.column = TRUE, 
                                             fill = NA, 
                                             align = 'right')


SPX_return$abnormal_returns<-SPX_return$Daily_Return-SPX_return$Rolling_3Y_Avg_Return

SPX_return$lagged_return<- lag(SPX_return$Daily_Return)

SPX_return<- SPX_return %>% 
  mutate(Date = as.Date(Date)) %>%  
  complete(Date = seq.Date(min(Date), max(Date), by="day"))

SPX_return<- SPX_return[SPX_return$Date %in% FilterDates,]

######################################## SURPRISES ###########################

IR_Lead <- read.csv("./DFF.csv")
IR_Lead$Date <- as.Date(IR_Lead$DATE, format = "%Y-%m-%d") # converting the date column
IR_Lead$DFF<- lead(IR_Lead$DFF)

IR_Lead<- IR_Lead %>% 
  mutate(Date = as.Date(Date)) %>%  
  complete(Date = seq.Date(min(Date), max(Date), by="day"))

IR_Lead <-na.locf(IR_Lead, fromLast = FALSE)
IR_Lead <- IR_Lead[IR_Lead$Date %in% FilterDates,][,-1]

IR_Surprises<- IR_Lead$DFF-Fed_Futures$FORWARD

######################################################################################
########################### CONSTRUCTION OF CORE DATASET FOR REGRESSIONS #############
######################################################################################

Core$return <- SPX_return$Daily_Return
Core$lagged_return <- as.numeric(SPX_return$lagged_return)
Core$abnormal_return <- as.numeric(SPX_return$abnormal_returns)
Core$IR<- IR_Lead$DFF
Core$Surprise<-IR_Surprises
Core$debt_equity<- SPX_DE$Net_Debt_Share
```

```{r Models based on Tone, results='asis'}
#All models based on Tone

simple_tone <- lm(abnormal_return ~ Tone, data = Core)
simple_tone_IR <- lm(abnormal_return ~ Tone + IR, data = Core)
simple_tone_LR <- lm(abnormal_return ~ Tone + IR + lagged_return, data = Core)
simple_tone_SUR <- lm(abnormal_return ~ Tone + IR + lagged_return + Surprise, data = Core)
simple_tone_DE <- lm(abnormal_return ~ Tone + IR + lagged_return + Surprise + debt_equity, data = Core)
```

```{r Models based on Unc}
#All models based on Unc
simple_unc <- lm(abnormal_return ~ Unc, data = Core)
simple_unc_IR <- lm(abnormal_return ~ Unc + IR, data = Core)
simple_unc_LR <- lm(abnormal_return ~ Unc + IR + lagged_return, data = Core)
simple_unc_SUR <- lm(abnormal_return ~ Unc + IR + lagged_return + Surprise, data = Core)
simple_unc_DE <- lm(abnormal_return ~ Con + IR + lagged_return + Surprise + debt_equity, data = Core)
```

```{r Models based on Con}
#All models based on Con
simple_con <- lm(abnormal_return ~ Con, data = Core)
simple_con_IR <- lm(abnormal_return ~ Con + IR, data = Core)
simple_con_LR <- lm(abnormal_return ~ Con + IR + lagged_return, data = Core)
simple_con_SUR <- lm(abnormal_return ~ Con + IR + lagged_return + Surprise, data = Core)
simple_con_DE <- lm(abnormal_return ~ Con + IR + lagged_return + Surprise + debt_equity, data = Core)
```

```{r Models based on Bert and Bert normed}
#All models based on Bert and Bert_normed
simple_bert <- lm(abnormal_return ~ Bert, data = Core)
simple_bert_IR <- lm(abnormal_return ~ Bert + IR, data = Core)
simple_bert_LR <- lm(abnormal_return ~ Bert + IR + lagged_return, data = Core)
simple_bert_SUR <- lm(abnormal_return ~ Bert + IR + lagged_return + Surprise, data = Core)
simple_bert_DE <- lm(abnormal_return ~ Bert + IR + lagged_return + Surprise + debt_equity, data = Core)

simple_bert_normed <- lm(abnormal_return ~ Bert_normed, data = Core)
simple_bert_normed_IR <- lm(abnormal_return ~ Bert_normed + IR, data = Core)
simple_bert_normed_LR <- lm(abnormal_return ~ Bert_normed + IR + lagged_return, data = Core)
simple_bert_normed_SUR <- lm(abnormal_return ~ Bert_normed + IR + lagged_return + Surprise, data = Core)
simple_bert_normed_DE <- lm(abnormal_return ~ Bert_normed + IR + lagged_return + Surprise + debt_equity, data = Core)
```

```{r "Trial", eval=FALSE, include=FALSE, results='asis'}

trial_tone<-lm(abnormal_return~Tone + IR + lagged_return + Surprise + debt_equity, data=Core)
trial_unc<-lm(abnormal_return~Unc + IR + lagged_return + Surprise + debt_equity, data=Core)
trial_con<-lm(abnormal_return~Con + IR + lagged_return + Surprise + debt_equity, data=Core)

stargazer(simple_tone, simple_con, simple_unc, 
          column.labels = c("Tone", "Unc", "Con"), header = F)
stargazer(trial_tone, trial_unc, trial_con,
          column.labels = c("Tone", "Unc", "Con"), header = F)


```

```{r Models including interaction terms}
#Interaction Models

interactions_tone <- lm(abnormal_return ~ Tone * debt_equity + IR + lagged_return + Surprise * debt_equity + debt_equity, data = Core)

interactions_unc<-lm(abnormal_return~Unc*debt_equity + IR + lagged_return + Surprise*debt_equity + debt_equity, data=Core)

interactions_con<-lm(abnormal_return~Con*debt_equity + IR + lagged_return + Surprise*debt_equity + debt_equity, data=Core)

interations_bert <- lm(abnormal_return~Bert*debt_equity + IR + lagged_return + Surprise*debt_equity + debt_equity, data=Core)

interactions_bert_normed <- lm(abnormal_return~Bert*debt_equity + IR + lagged_return + Surprise*debt_equity + debt_equity, data=Core)


```

```{r Stargazer Tables, eval=FALSE, include=FALSE}
#Tables
stargazer(simple_tone, simple_tone_IR, simple_tone_LR, simple_tone_SUR, simple_tone_DE, interactions_tone, column.labels = c("Tone", "Cons", "Unc"), header = FALSE)



```

## Bibliography {#sec-bibliography}

Möller, R., & Reichmann, D. (2021). ECB language and stock returns--A textual analysis of ECB press conferences. The Quarterly Review of Economics and Finance, 80, 590-604.
